apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - agentregistry.yaml
  - kagent.yaml
  - phoenix.yaml
  - qdrant.yaml
  - llama-cpp-embeddings.yaml
  - ollama.yaml
  - embeddings-route.yaml
  - agent-embeddings.yaml
  - llmd.yaml
  - mcp-servers.yaml
  - agent-retrieval.yaml
  - neo4j.yaml
  - opentelemetry-demo.yaml
  - mlflow.yaml
  - mlflow-otel-collector.yaml
  - ngrok-operator.yaml

patches:
  - path: patches/k8s-agent-sidecar.yaml
    target:
      kind: Deployment
      name: k8s-agent
      namespace: kagent
  - path: patches/k8s-agent-modelconfig.yaml
    target:
      kind: Agent
      name: k8s-agent
      namespace: kagent
