apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - agentregistry.yaml
  - kagent.yaml
  - phoenix.yaml
  - qdrant.yaml
  - llama-cpp-embeddings.yaml

patches:
  - path: patches/k8s-agent-sidecar.yaml
    target:
      kind: Deployment
      name: k8s-agent
      namespace: kagent
